# Generated by Django 3.1 on 2021-03-20 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onlineuser',
            name='joined_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', to_field='groupid'),
        ),
        migrations.AddField(
            model_name='onlineuser',
            name='online_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='message_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='target_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', to_field='groupid'),
        ),
        migrations.AddField(
            model_name='membership',
            name='the_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', to_field='groupid'),
        ),
        migrations.AddField(
            model_name='membership',
            name='the_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='hash_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_groups', through='groups.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptedclient',
            name='accepted_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acceptedclient',
            name='entered_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', to_field='groupid'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('member', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='onlineuser',
            unique_together={('joined_group', 'online_user')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('the_group', 'the_member')},
        ),
        migrations.AlterUniqueTogether(
            name='acceptedclient',
            unique_together={('entered_group', 'accepted_client')},
        ),
    ]
