# Generated by Django 3.0.6 on 2020-05-20 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='chat_permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='choose_video_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='playback_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('member', 'group')},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='permit',
        ),
    ]
