# Generated by Django 3.0.5 on 2020-04-21 11:38

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[(groups.models.StatusChoice['state0'], 'video was not selected by owner'), (groups.models.StatusChoice['state1'], 'video validation is checking'), (groups.models.StatusChoice['state2'], 'video is playing')], default='video was not selected by owner', max_length=50),
        ),
    ]
