# Generated by Django 3.0.5 on 2020-04-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='video_hash',
            field=models.CharField(blank=True, default='No hash yet!', max_length=100),
        ),
    ]
