# Generated by Django 3.1 on 2021-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='test_1',
            field=models.BooleanField(default=False),
        ),
    ]
