# Generated by Django 3.1 on 2021-05-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_test_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='test_1',
            new_name='photo',
        ),
    ]
