# Generated by Django 3.1 on 2021-04-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='aux_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
