# Generated by Django 3.0.5 on 2020-04-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200419_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='status',
        ),
    ]
