# Generated by Django 3.0.6 on 2020-05-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-date_sent']},
        ),
    ]
