# Generated by Django 3.0.5 on 2020-04-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_video_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'video was not selected by owner'), (1, 'video validation is checking'), (2, 'video is playing')], default=0),
        ),
    ]
