# Generated by Django 3.1 on 2021-04-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_aux_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['aux_count']},
        ),
    ]
