# Generated by Django 3.0.4 on 2020-05-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_message_onlineuser'),
        ('groups', '0004_onlineuser'),
    ]

    operations = [
    ]
