# Generated by Django 3.1.7 on 2021-06-02 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_preview', models.CharField(blank=True, max_length=100)),
                ('notification_type', models.IntegerField(choices=[(1, 'Friend-Requests-Count'), (2, 'Group-Requests-Count'), (3, 'Friend-Request-State'), (4, 'Group-Request-State'), (5, 'New-Follower'), (6, 'Group-Notice-Count'), (7, 'Group-Notice'), (8, 'Group-Invite-Count')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_from_group', to='groups.group', to_field='groupid')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_to_user', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
