# Generated by Django 3.1.7 on 2021-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(default='Hi there! Now available on vshare.', max_length=80),
        ),
    ]
