# Generated by Django 3.0.5 on 2020-05-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
