# Generated by Django 3.1.7 on 2021-04-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_private',
        ),
    ]
