# Generated by Django 3.0.6 on 2020-05-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendship'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('who_follows', 'who_is_followed')},
        ),
    ]
