# Generated by Django 3.1 on 2021-05-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.chat'),
        ),
    ]
