# Generated by Django 3.1 on 2021-04-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_account_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_private',
        ),
    ]
