# Generated by Django 3.1 on 2021-05-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_directmessage_chat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('starter_user', 'non_starter_user')},
        ),
    ]
